-- PlaceGuard: database-owned authorization, workflow enforcement, and tamper-evident audit trail.
create extension if not exists pgcrypto with schema extensions;
create type public.app_role as enum ('student','company','coordinator','tnp_head','admin');
create type public.drive_status as enum ('draft','open','closed','locked','completed');
create type public.application_status as enum ('APPLIED','ELIGIBLE','INELIGIBLE','SHORTLISTED','REJECTED','SELECTED');
create type public.proposal_action as enum ('ADD','REMOVE');
create type public.proposal_status as enum ('PENDING','APPROVED','REJECTED','BLOCKED');
create type public.approval_decision as enum ('APPROVED','REJECTED');
create type public.anomaly_severity as enum ('LOW','MEDIUM','HIGH','CRITICAL');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null check (length(trim(name)) between 1 and 160), email text not null unique, role public.app_role not null default 'student', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.students (id uuid primary key default gen_random_uuid(), profile_id uuid not null unique references public.profiles(id) on delete cascade, roll_number text not null unique, branch text not null, year smallint not null check (year between 1 and 8), cgpa numeric(3,2) not null check (cgpa between 0 and 10), backlogs smallint not null default 0 check (backlogs >= 0), skills text[] not null default '{}', resume_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.companies (id uuid primary key default gen_random_uuid(), profile_id uuid not null unique references public.profiles(id) on delete cascade, company_name text not null, website text, description text, verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.drives (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id), title text not null, description text not null default '', role_name text not null, deadline timestamptz not null, status public.drive_status not null default 'draft', created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (deadline > created_at));
create table public.eligibility_rules (id uuid primary key default gen_random_uuid(), drive_id uuid not null unique references public.drives(id) on delete cascade, min_cgpa numeric(3,2) not null check (min_cgpa between 0 and 10), allowed_branches text[] not null check (cardinality(allowed_branches) > 0), max_backlogs smallint not null check (max_backlogs >= 0), required_skills text[] not null default '{}', locked boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.applications (id uuid primary key default gen_random_uuid(), drive_id uuid not null references public.drives(id), student_id uuid not null references public.students(id), applied_at timestamptz not null default now(), status public.application_status not null default 'APPLIED', unique (drive_id, student_id));
create table public.eligibility_results (id uuid primary key default gen_random_uuid(), application_id uuid not null unique references public.applications(id) on delete cascade, eligible boolean not null, failed_rules text[] not null default '{}', checked_at timestamptz not null default now(), engine_version text not null);
create table public.shortlist_proposals (id uuid primary key default gen_random_uuid(), drive_id uuid not null references public.drives(id), student_id uuid not null references public.students(id), proposed_by uuid not null references public.profiles(id), action public.proposal_action not null, reason text not null check (length(trim(reason)) between 5 and 1000), status public.proposal_status not null default 'PENDING', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.approvals (id uuid primary key default gen_random_uuid(), proposal_id uuid not null unique references public.shortlist_proposals(id), reviewed_by uuid not null references public.profiles(id), decision public.approval_decision not null, reason text not null check (length(trim(reason)) between 5 and 1000), created_at timestamptz not null default now());
create table public.shortlists (id uuid primary key default gen_random_uuid(), drive_id uuid not null references public.drives(id), student_id uuid not null references public.students(id), status text not null default 'SHORTLISTED' check (status in ('SHORTLISTED','REMOVED')), added_at timestamptz not null default now(), approved_by uuid not null references public.profiles(id), locked_at timestamptz, unique (drive_id, student_id));
create table public.audit_commits (id uuid primary key default gen_random_uuid(), sequence_number bigint generated always as identity unique, actor_id uuid references public.profiles(id), actor_role public.app_role, action_type text not null, entity_type text not null, entity_id uuid, reason text, metadata jsonb not null default '{}', created_at timestamptz not null default now(), previous_hash text not null, event_hash text not null unique, status text not null check (status in ('SUCCESS','BLOCKED','FAILED')));
create table public.anomaly_alerts (id uuid primary key default gen_random_uuid(), type text not null, severity public.anomaly_severity not null, description text not null, drive_id uuid references public.drives(id), audit_commit_id uuid references public.audit_commits(id), risk_score smallint not null check (risk_score between 0 and 100), status text not null default 'OPEN' check (status in ('OPEN','RESOLVED')), created_at timestamptz not null default now(), resolved_at timestamptz, resolved_by uuid references public.profiles(id));
create table public.notifications (id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.profiles(id), title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.admin_access_requests (id uuid primary key default gen_random_uuid(), admin_id uuid not null references public.profiles(id), resource_type text not null, resource_id uuid, reason text not null check (length(trim(reason)) >= 10), authorized_by uuid references public.profiles(id), status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')), created_at timestamptz not null default now(), accessed_at timestamptz);
create table public.placement_outcomes (id uuid primary key default gen_random_uuid(), drive_id uuid not null references public.drives(id), student_id uuid not null references public.students(id), outcome text not null check (outcome in ('SELECTED','REJECTED','WAITLISTED')), recorded_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), unique(drive_id, student_id));
create index drives_company_status_idx on public.drives(company_id,status); create index applications_student_idx on public.applications(student_id); create index applications_drive_idx on public.applications(drive_id); create index proposals_drive_status_idx on public.shortlist_proposals(drive_id,status); create index audit_entity_idx on public.audit_commits(entity_type,entity_id,sequence_number desc); create index anomalies_drive_status_idx on public.anomaly_alerts(drive_id,status);

create function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at(); create trigger students_updated before update on public.students for each row execute function public.set_updated_at(); create trigger companies_updated before update on public.companies for each row execute function public.set_updated_at(); create trigger drives_updated before update on public.drives for each row execute function public.set_updated_at(); create trigger rules_updated before update on public.eligibility_rules for each row execute function public.set_updated_at(); create trigger proposals_updated before update on public.shortlist_proposals for each row execute function public.set_updated_at();
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name,email) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'name',''),split_part(new.email,'@',1)),new.email); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and is_active $$;
create function public.is_company_owner(p_drive uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.drives d join public.companies c on c.id=d.company_id where d.id=p_drive and c.profile_id=auth.uid()) $$;
create function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select public.current_role() in ('coordinator','tnp_head','admin') $$;

create function public.record_audit(p_action text,p_entity_type text,p_entity_id uuid,p_reason text default null,p_metadata jsonb default '{}',p_status text default 'SUCCESS') returns uuid language plpgsql security definer set search_path=public as $$ declare v_previous text; v_hash text; v_id uuid; v_role public.app_role; v_payload jsonb; begin perform pg_advisory_xact_lock(7142026); select event_hash into v_previous from public.audit_commits order by sequence_number desc limit 1; v_previous:=coalesce(v_previous,'GENESIS'); v_role:=public.current_role(); v_payload:=jsonb_build_object('actor_id',auth.uid(),'actor_role',v_role,'action_type',p_action,'entity_type',p_entity_type,'entity_id',p_entity_id,'reason',p_reason,'metadata',coalesce(p_metadata,'{}'::jsonb),'status',p_status); v_hash:=encode(extensions.digest(v_payload::text || v_previous,'sha256'),'hex'); insert into public.audit_commits(actor_id,actor_role,action_type,entity_type,entity_id,reason,metadata,previous_hash,event_hash,status) values(auth.uid(),v_role,p_action,p_entity_type,p_entity_id,p_reason,coalesce(p_metadata,'{}'),v_previous,v_hash,p_status) returning id into v_id; return v_id; end $$;
create function public.prevent_audit_mutation() returns trigger language plpgsql as $$ begin raise exception 'Audit commits are append-only'; end $$;
create trigger audit_no_update before update or delete on public.audit_commits for each row execute function public.prevent_audit_mutation();
create function public.verify_audit_chain() returns jsonb language plpgsql security definer set search_path=public as $$ declare r record; v_previous text:='GENESIS'; v_expected text; v_checked int:=0; begin for r in select * from public.audit_commits order by sequence_number loop v_checked:=v_checked+1; v_expected:=encode(extensions.digest(jsonb_build_object('actor_id',r.actor_id,'actor_role',r.actor_role,'action_type',r.action_type,'entity_type',r.entity_type,'entity_id',r.entity_id,'reason',r.reason,'metadata',r.metadata,'status',r.status)::text || v_previous,'sha256'),'hex'); if r.previous_hash <> v_previous or r.event_hash <> v_expected then return jsonb_build_object('valid',false,'checked',v_checked,'brokenAt',r.sequence_number); end if; v_previous:=r.event_hash; end loop; return jsonb_build_object('valid',true,'checked',v_checked,'brokenAt',null); end $$;

create function public.apply_to_drive(p_drive uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare s public.students%rowtype; r public.eligibility_rules%rowtype; d public.drives%rowtype; a uuid; failed text[]:='{}'; ok boolean; begin if public.current_role()<>'student' then raise exception 'Not authorized'; end if; select * into s from public.students where profile_id=auth.uid(); select * into d from public.drives where id=p_drive; select * into r from public.eligibility_rules where drive_id=p_drive; if d.status<>'open' or d.deadline <= now() then perform public.record_audit('DEADLINE_VIOLATION','drive',p_drive,'Application blocked after deadline','{}','BLOCKED'); raise exception 'Drive is not accepting applications'; end if; if s.cgpa<r.min_cgpa then failed:=array_append(failed,format('CGPA %s is below required minimum %s.',s.cgpa,r.min_cgpa)); end if; if s.backlogs>r.max_backlogs then failed:=array_append(failed,'Backlog limit exceeded.'); end if; if not (lower(s.branch)=any(select lower(x) from unnest(r.allowed_branches) x)) then failed:=array_append(failed,'Branch is not allowed.'); end if; if exists(select 1 from unnest(r.required_skills) x where not lower(x)=any(select lower(y) from unnest(s.skills) y)) then failed:=array_append(failed,'Required skills are missing.'); end if; ok:=cardinality(failed)=0; if not ok then perform public.record_audit('ELIGIBILITY_CHECKED','drive',p_drive,array_to_string(failed,' '),jsonb_build_object('eligible',false),'BLOCKED'); raise exception 'You do not meet the eligibility requirements'; end if; insert into public.applications(drive_id,student_id,status) values(p_drive,s.id,'ELIGIBLE') returning id into a; insert into public.eligibility_results(application_id,eligible,engine_version) values(a,true,'1.0.0'); perform public.record_audit('APPLICATION_SUBMITTED','application',a,null,jsonb_build_object('drive_id',p_drive)); perform public.record_audit('ELIGIBILITY_CHECKED','application',a,null,jsonb_build_object('eligible',true)); return a; end $$;
create function public.create_shortlist_proposal(p_drive uuid,p_student uuid,p_action public.proposal_action,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; d public.drives%rowtype; er boolean; c uuid; begin if public.current_role()<>'coordinator' then perform public.record_audit('UNAUTHORIZED_ACTION','drive',p_drive,'Only coordinators may propose shortlist changes','{}','BLOCKED'); raise exception 'Not authorized'; end if; select * into d from public.drives where id=p_drive; if d.deadline<=now() or d.status in ('locked','completed','closed') then c:=public.record_audit('DEADLINE_VIOLATION','drive',p_drive,'Drive deadline has passed','{}','BLOCKED'); insert into public.anomaly_alerts(type,severity,description,drive_id,audit_commit_id,risk_score) values('LATE_ACTION','CRITICAL','Shortlist modification was attempted after deadline.',p_drive,c,70); raise exception 'Drive deadline has passed'; end if; select er.eligible into er from public.applications a join public.eligibility_results er on er.application_id=a.id where a.drive_id=p_drive and a.student_id=p_student; if p_action='ADD' and coalesce(er,false)=false then c:=public.record_audit('UNAUTHORIZED_ACTION','drive',p_drive,'Ineligible candidate addition proposed',jsonb_build_object('student_id',p_student),'BLOCKED'); insert into public.anomaly_alerts(type,severity,description,drive_id,audit_commit_id,risk_score) values('ELIGIBILITY_VIOLATION','HIGH','An ineligible candidate was proposed for addition.',p_drive,c,30); end if; insert into public.shortlist_proposals(drive_id,student_id,proposed_by,action,reason,status) values(p_drive,p_student,auth.uid(),p_action,p_reason,case when p_action='ADD' and coalesce(er,false)=false then 'BLOCKED' else 'PENDING' end) returning id into v_id; perform public.record_audit(case when p_action='ADD' then 'SHORTLIST_ADD_PROPOSED' else 'SHORTLIST_REMOVE_PROPOSED' end,'shortlist_proposal',v_id,p_reason,'{}',case when coalesce(er,true) then 'SUCCESS' else 'BLOCKED' end); return v_id; end $$;
create function public.review_proposal(p_proposal uuid,p_decision public.approval_decision,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare p public.shortlist_proposals%rowtype; begin if public.current_role()<>'tnp_head' then raise exception 'Not authorized'; end if; select * into p from public.shortlist_proposals where id=p_proposal for update; if p.proposed_by=auth.uid() then raise exception 'Separation of duties violation'; end if; if p.status<>'PENDING' then raise exception 'Proposal is not pending'; end if; if p_decision='APPROVED' and p.reason ilike '%exception%' and length(trim(p_reason))<10 then raise exception 'Documented exception reason required'; end if; insert into public.approvals(proposal_id,reviewed_by,decision,reason) values(p_proposal,auth.uid(),p_decision,p_reason); update public.shortlist_proposals set status=case when p_decision='APPROVED' then 'APPROVED' else 'REJECTED' end where id=p_proposal; if p_decision='APPROVED' then insert into public.shortlists(drive_id,student_id,status,approved_by) values(p.drive_id,p.student_id,case when p.action='ADD' then 'SHORTLISTED' else 'REMOVED' end,auth.uid()) on conflict(drive_id,student_id) do update set status=excluded.status,approved_by=excluded.approved_by,added_at=now(); end if; perform public.record_audit(case when p_decision='APPROVED' then 'PROPOSAL_APPROVED' else 'PROPOSAL_REJECTED' end,'shortlist_proposal',p_proposal,p_reason,'{}'); end $$;
create function public.lock_shortlist(p_drive uuid) returns void language plpgsql security definer set search_path=public as $$ begin if public.current_role()<>'tnp_head' then raise exception 'Not authorized'; end if; update public.drives set status='locked' where id=p_drive and status in ('open','closed'); update public.shortlists set locked_at=now() where drive_id=p_drive and locked_at is null; perform public.record_audit('SHORTLIST_LOCKED','drive',p_drive,null,'{}'); end $$;

alter table public.profiles enable row level security; alter table public.students enable row level security; alter table public.companies enable row level security; alter table public.drives enable row level security; alter table public.eligibility_rules enable row level security; alter table public.applications enable row level security; alter table public.eligibility_results enable row level security; alter table public.shortlist_proposals enable row level security; alter table public.approvals enable row level security; alter table public.shortlists enable row level security; alter table public.audit_commits enable row level security; alter table public.anomaly_alerts enable row level security; alter table public.notifications enable row level security; alter table public.admin_access_requests enable row level security; alter table public.placement_outcomes enable row level security;
create policy profiles_self_read on public.profiles for select using (id=auth.uid() or public.is_staff()); create policy profiles_admin_update on public.profiles for update using (public.current_role()='admin') with check (public.current_role()='admin');
create policy students_self_or_staff on public.students for select using (profile_id=auth.uid() or public.is_staff()); create policy companies_public_read on public.companies for select using (true); create policy companies_owner_update on public.companies for update using(profile_id=auth.uid()) with check(profile_id=auth.uid());
create policy drives_open_or_owner on public.drives for select using (status='open' or public.is_company_owner(id) or public.is_staff()); create policy drives_company_insert on public.drives for insert with check (public.current_role()='company' and created_by=auth.uid() and exists(select 1 from public.companies c where c.id=company_id and c.profile_id=auth.uid())); create policy drives_company_update on public.drives for update using(public.is_company_owner(id)) with check(public.is_company_owner(id));
create policy rules_read_for_drive on public.eligibility_rules for select using (exists(select 1 from public.drives d where d.id=drive_id and (d.status='open' or public.is_company_owner(d.id) or public.is_staff()))); create policy rules_company_write on public.eligibility_rules for all using (exists(select 1 from public.drives d where d.id=drive_id and public.is_company_owner(d.id) and d.status='draft') and not locked) with check (exists(select 1 from public.drives d where d.id=drive_id and public.is_company_owner(d.id) and d.status='draft') and not locked);
create policy applications_own_company_staff on public.applications for select using (student_id in (select id from public.students where profile_id=auth.uid()) or public.is_company_owner(drive_id) or public.is_staff()); create policy results_matching_application on public.eligibility_results for select using (exists(select 1 from public.applications a where a.id=application_id and (a.student_id in (select id from public.students where profile_id=auth.uid()) or public.is_company_owner(a.drive_id) or public.is_staff())));
create policy proposals_staff_or_company on public.shortlist_proposals for select using (public.is_staff() or public.is_company_owner(drive_id)); create policy approvals_staff_or_company on public.approvals for select using (public.is_staff() or exists(select 1 from public.shortlist_proposals p where p.id=proposal_id and public.is_company_owner(p.drive_id))); create policy shortlist_visible on public.shortlists for select using (public.is_staff() or public.is_company_owner(drive_id) or student_id in (select id from public.students where profile_id=auth.uid()));
create policy audit_company_or_staff on public.audit_commits for select using (public.is_staff() or (entity_type='drive' and public.is_company_owner(entity_id)) or (metadata ? 'drive_id' and public.is_company_owner((metadata->>'drive_id')::uuid))); create policy anomalies_staff_or_company on public.anomaly_alerts for select using (public.is_staff() or public.is_company_owner(drive_id)); create policy notifications_own on public.notifications for select using(recipient_id=auth.uid()); create policy notifications_own_update on public.notifications for update using(recipient_id=auth.uid()) with check(recipient_id=auth.uid()); create policy admin_requests_owner_or_head on public.admin_access_requests for select using(admin_id=auth.uid() or public.current_role()='tnp_head'); create policy outcomes_visible on public.placement_outcomes for select using(public.is_staff() or public.is_company_owner(drive_id) or student_id in (select id from public.students where profile_id=auth.uid()));
grant execute on function public.apply_to_drive(uuid), public.create_shortlist_proposal(uuid,uuid,public.proposal_action,text), public.review_proposal(uuid,public.approval_decision,text), public.lock_shortlist(uuid), public.verify_audit_chain() to authenticated;
